[Variables]

CommunityAppRunOnce=0

; ----- Add/Modify your variables below: ----------------

GetQuote=.*<item>.*<title>(.*)</title>.*<description>"(.*)"</description>

QuoteNumber=1
SwitchTime=20

AppName=Daily Quotes
AppAuthor=Bunz
AppVersion=1.0.3

Quote1=The price of greatness is responsibility.
Author1=Winston Churchill

Quote2=The happiest people seem to be those who have no particular cause for being happy except that they are so.
Author2=William Inge

Quote3=Man is a creature who lives not upon bread alone, but primarily by catchwords.
Author3=Robert Louis Stevenson
