[Variables]
Skin.Width=(#DropdownMenuWidth#+2-(#DropdownMenuCutout#*2))
Skin.Height=100

Key=#SKINSPATH#Droptop\@Resources\GlobalVar\UserSettings.inc
Key2=#SKINSPATH#Droptop Community Apps\Apps\Random_Theme_Changer-Mike_Boynton\Variables\Variables.inc

CurrentItemX=#DropdownMenuWidth#
CurrentItemY=#DropdownItemHeight#
CurrentBoxX=#DropdownMenuWidth#
CurrentFontSize=#DropdownItemFontSize#
CurrentTheme=Macintosh Theme

hb=22
OnOff=0
OnOffText=On
InfoOnOffText=Off
NumBoxes=1
RoundTo=1

Name=Random Theme Changer
Author=Mike Boynton
Version=1.1
