[Variables]

NameBox1=Bridge Constructor The Walking Dead
GameBox1=["com.epicgames.launcher://apps/39697c68e46b48d2b75e17bdc417d859%3A16d6fbdf1f784345bf6d2e01a3e16e37%3A998af0ab527c493baefb8049250c9a0e?action=launch&silent=true"]

NameBox2=Blasphemous
GameBox2=["C:\Games\Blasphemous\Blasphemous.exe"]

NameBox3=New Game
GameBox3=

NameBox4=New Game
GameBox4=

NameBox5=New Game
GameBox5=

NameBox6=New Game
GameBox6=

NameBox7=New Game
GameBox7=

NameBox8=New Game
GameBox8=

NameBox9=New Game
GameBox9=

NameBox10=New Game
GameBox10=

NameBox11=New Game
GameBox11=

NameBox12=New Game
GameBox12=
